### ISSUE TITLE
classify each connector according to rubric in docs

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#1305]
https://docs.meltano.com/cloud/connectors

**Comment by pnadolny13** [comment]
TODO:
- [ ] add quality attribute to required schema
- [ ] skip returning quality as an attribute of the API
- [ ] identify quality using data
- [ ] check quality against mnaual

**Comment by pnadolny13** [comment]
I'd love to get the connector quality matrix https://docs.meltano.com/cloud/connectors#connector-quality-matrix evaluation into code so its less judgement based and allows us to automate the tagging of quality and detecting changes to quality. I think we have all the data that we need to automate this but the current state of the matrix is a bit tricky to implement because some of it is up for interpretation.

In my mind we could have them all recalculated on a weekly basis and a PR/issue opened to change any.

1. Do we think its possible to automate this and is that what we're hoping to do?
2. What happens if an official maintained connector has < 5 projects usage, isnt SDK based, or isnt responsive? Hopefully this is never the case but the usage attribute in particular is out of our control.
3. Could an SDK based connector with low usage or low responsiveness end up in the bronze category?
4. Could a partner connector ever be lower that silver?
5. Maybe there are matrix attributes that automatically elevate a connector. Like if its official then its gold, if its partner it's never lower than silver, if its SDK its never lower than silver, if its >5 projects it's never lower than silver, if it's low or unknown responsiveness then its never higher than bronze, etc. 

@tayloramurphy any thoughts? Its pretty tricky to make definitive rules around this.

**Comment by tayloramurphy** [comment]
> Do we think its possible to automate this and is that what we're hoping to do?

Automation would be great! I figured we could take a first pass with these parameters and then see what falls out. 

> What happens if an official maintained connector has < 5 projects usage, isnt SDK based, or isnt responsive? Hopefully this is never the case but the usage attribute in particular is out of our control.

I don't think it could ever happen that an official one isn't SDK-based going forward... But if it isn't based on the SDK I don't want it to be Gold. 

> Could an SDK based connector with low usage or low responsiveness end up in the bronze category?

My sense was unlikely, but possible. Being based on the SDK general means it's of a higher quality. But perhaps we should have something about stream coverage in the criteria?

> Could a partner connector ever be lower that silver?

Possibly, but we should really strive to not be in that situation.

> Maybe there are matrix attributes that automatically elevate a connector. Like if its official then its gold, if its partner it's never lower than silver, if its SDK its never lower than silver, if its >5 projects it's never lower than silver, if it's low or unknown responsiveness then its never higher than bronze, etc.

Those seem fairly reasonable. I'd say let's take a first pass and see what shakes out and where we feel it falls short. My goal with the matrix wasn't to be 100% prescriptive but rather give guidance on what folks could typically expect from a Gold connector. Maybe we say 80% of connectors have these attributes for a given category (or something like that) @pnadolny13

**Comment by pnadolny13** [comment]
> I'd say let's take a first pass and see what shakes out and where we feel it falls short. My goal with the matrix wasn't to be 100% prescriptive but rather give guidance on what folks could typically expect from a Gold connector. Maybe we say 80% of connectors have these attributes for a given category (or something like that)

@tayloramurphy sounds good to me. I dont think its a problem to have it coded in a more nuanced/opinionated way than how we communicate it to users. I'm also liking that automating this will allow us to flag projects that are dropping quality so we can potentially intervene but we'll be in charge of approving promotions/demotions so we can give a grace period or override based on judgement.

**Comment by pnadolny13** [comment]
Closed by https://github.com/meltano/hub/pull/1347
