### ISSUE TITLE
Update dbt plugin definitions to `dbt 1.1`

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#560]
dbt core and adapters are updated to `~=1.1`. We need to review them and update as appropriate on the Hub!

* https://github.com/dbt-labs/dbt-core/releases
* https://github.com/dbt-labs/dbt-bigquery/releases

**Comment by aaronsteers** [comment]
Let's pick this up as soon as we have the new integration tests that @pandemicsyn is working on.

- https://github.com/meltano/meltano/issues/6218

@pandemicsyn - Do you want to tackle this at the same time or should we pick it up after. 

If after, I think @kgpayne would be a good one to tackle this because he knows what to look for on the dbt side compatibility-wise.

**Comment by tayloramurphy** [comment]
@cjohnhanson do we have any CI tests on the Meltano side to validate that this upgrade hasn't broken anything? With the new integration tests Florian added I think we could add a few. It may be a separate question though whether or not there's any sort of automated cross-project CI that's going to run.

**Comment by tayloramurphy** [comment]
@cjohnhanson I think it's appropriate to have integration tests like https://github.com/meltano/meltano/blob/main/docs/example-library/meltano-run/index.md#getting-dbt-involved that test plugin-specific functionality. Perhaps what's there is sufficient for now but I do want to make sure Meltano changes aren't breaking plugins 😄
