### ISSUE TITLE
Revamp: Add netlify build for gridsome version

### ISSUE THREAD

**Issue by rwfeather** [meltano/hub#647]

**Comment by alexmarple** [comment]
@rwfeather I added a netlify toml in and the site now builds and deploys if we make a git commit. it's still failing if we trigger a normal build because that looks at the `gridsome-main` branch which doesn't currently have the site in it. once we merge `minimum-viable-gridsome` into `gridsome-main` it should work perfectly.

As with all things, please check to make sure I'm not wrong about that! But it seems all set up correctly.
