### ISSUE TITLE
"Last Updated At" is wrong for tap-salesforce (on GitLab)

### ISSUE THREAD

**Issue by DouweM** [meltano/hub#715]
https://hub.meltano.com/taps/salesforce says “Last Updated At 02 Nov 2018”, while the last commit on https://gitlab.com/meltano/tap-salesforce is from 7 months ago. Not sure if this is related to it being on GitLab not GitHub.

**Comment by DouweM** [comment]
cc @tayloramurphy @pnadolny13

**Comment by pnadolny13** [comment]
@DouweM ah I think I know whats going on. Those repo metrics should only come through for github repos. It looks like its referencing https://github.com/meltano/tap-salesforce instead of the gitlab repo. Right now we send repo metrics without the github prefix i.e. `meltano/tap-salesforce` with the understanding that we only pull from github. In the next metrics iteration we're sending the full repo url so `https://github.com/meltano/tap-salesforce`.

This is a bug with the way that we're rendering the repo data. I don't think were checking to make sure the variant repo is a github repo before matching (line https://github.com/meltano/hub/blob/79819ea04601ebde833fd781764403f88481972c/_plugins/plugin_enricher.rb#L78) on namespace so in this case we have an accidental match. We should probably check that the variant repo matches the namespace AND is a github repo until the new metrics are in use. Potentially needing to update https://github.com/meltano/hub/blob/79819ea04601ebde833fd781764403f88481972c/_layouts/meltano_plugin.html#L67 as well.

**Comment by DouweM** [comment]
@pnadolny13 Ah, makes sense! If you think you can fix this in a few minutes, feel free to submit a PR -- that'll be faster than waiting for this to make it onto the engineering board :)

**Comment by pnadolny13** [comment]
@DouweM I opened https://github.com/meltano/hub/pull/719 that fixes it!
