### ISSUE TITLE
bug: Plugins showing duplicate variants when a plugin of a different type exists with the same name

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#898]
https://hub.meltano.com/extractors/tap-zendesk/ is showing meltano as a default variant but that's coming from the `transforms`

**Comment by tayloramurphy** [comment]
@aaronsteers I'm going to assign this one to @cjohnhanson as this is a pretty bad usability bug and with Florian's EDK PRs landing soon is causing weird problems too!

<img width="288" alt="Screen Shot 2022-10-14 at 3 41 21 PM" src="https://user-images.githubusercontent.com/5394188/195939849-3b99129d-3a2c-4263-83a5-cf43597250a2.png">

**Comment by aaronsteers** [comment]
@cjohnhanson, @tayloramurphy - As of today, this bumped to higher priority; with the EDK `utility` samples launching under the same names as their originals, we're seeing duplicates again for all of those.

This won't be solved by removing `transforms` from the mix, so the only solution is probably to key and join those based on the combination of `plugin_type` and `name` instead of joining solely on `name`.

cc @rwfeather

**Comment by aaronsteers** [comment]
@rwfeather - I'm adding to your assignment board. Do you think you can help tackle this this week?
